### PR TITLE
serious conflicts between property and denotation parsing and serialization

### PR DESCRIPTION
**Pull request by eparejatobes**

### CODE REVIEW

**Comment by laughedelic** [comment]
Let's rename `ArghAGHGH` to something normal and merge this?

**Comment by laughedelic** [comment]
@eparejatobes please, release 0.7.1 with this fix. I need it for MG7

**Comment by eparejatobes** [comment]
@laughedelic published

**Comment by eparejatobes** [comment]
This is already fixed in master 94dd86c better to close this unmerged

**Comment by laughedelic** [comment]
ok. thanks

**Comment by laughedelic** [comment]
aghm.. but then we won't have release notes in master "_

**Comment by eparejatobes** [comment]
we can merge master into this branch, keeping master in case of conflicts

**Pull request closed without merging**
