### PR TITLE
any/all for building predicates on KLists

### PR DESCRIPTION
**Pull request by eparejatobes**

### CODE REVIEW

**Comment by eparejatobes** [comment]
All this should be non-breaking, and included in `0.8.1`.

**Comment by laughedelic** [comment]
Nope, it should be `0.9.0`:

> - Patch version Z (x.y.Z | x > 0) MUST be incremented if only backwards compatible bug fixes are introduced. A bug fix is defined as an internal change that fixes incorrect behavior.
> - Minor version Y (x.Y.z | x > 0) MUST be incremented if new, backwards compatible functionality is introduced to the public API.

http://semver.org

**Comment by eparejatobes** [comment]
@laughedelic your carbon-based predicate evaluator has a bug :stuck_out_tongue:

**Comment by eparejatobes** [comment]
do we need syntax for this? with what we have here in 8211fa7 the common use case would be

``` scala
def doSomething[L <: AnyKList](l: L)(implicit
  p: all[isBlue] isTrueOn L
): L = l 
```

**Comment by eparejatobes** [comment]
modulo syntax, LGTM

**Comment by laughedelic** [comment]
I think no syntax is necessary for this

**Comment by eparejatobes** [comment]
fine merging

**Pull request merged**
