### PR TITLE
better names for record-related types

### PR DESCRIPTION
**Pull request by eparejatobes**

### CODE REVIEW

**Comment by eparejatobes** [comment]
ping @laughedelic

**Comment by laughedelic** [comment]
Cool :+1: 
`□` is a bit too much, I think, but anyway. what is the latex name for this symbol?

**Comment by eparejatobes** [comment]
OK merging then. `\square` in LaTeX (`amsmath` required maybe?)

**Comment by laughedelic** [comment]
:trollface:

**Pull request merged**
