### PR TITLE
releasing 0.6.0

### PR DESCRIPTION
**Pull request by eparejatobes**

### CODE REVIEW

**Comment by laughedelic** [comment]
Why am I assigned?

**Comment by eparejatobes** [comment]
why not?

**Comment by eparejatobes** [comment]
:)

**Comment by laughedelic** [comment]
It's just not clear, whether you want me to do this release, or review something or what ")

**Comment by eparejatobes** [comment]
I'm releasing a `RC1` before

**Comment by laughedelic** [comment]
I promised to do here something yesterday, but I forgot what it was.. "_

**Comment by laughedelic** [comment]
please, before releasing, rename the `ohnosequences.cosas.equals` object, it's conflicting with something else

**Pull request merged**
