### PR TITLE
simpler records?

### PR DESCRIPTION
**Pull request by eparejatobes**
this could work:

``` scala
package buh

import ohnosequences.cosas._, typeSets._, types._, properties._

trait AnyRecord extends AnyType {

  type Properties <: AnyTypeSet
  type Raw <: AnyTypeSet
}


case object nrec extends AnyRecord {

  type Properties = ∅
  type Raw = ∅

  val label = "emtpy record"
}
case class :>:[P <: AnyProperty, R <: AnyRecord](val head: P, val tail: R) extends AnyRecord {

  type Properties = P :~: R#Properties
  type Raw = ValueOf[P] :~: R#Raw

  val label = s"${head.label} + ${tail.label}"
}

class Rec[R <: AnyRecord](val r: R)

object doSomething {
  type nrec = nrec.type
  case object a extends Property[String]("a"); type a = a.type
  case object b extends Property[Int]("b"); type b = b.type

  object ab extends :>:(a, :>:(b, nrec))

  val abAgain = :>:(a, :>:(b, nrec))

  val zz: ValueOf[ab.type] = ab := (a("aaaa") :~: b(2) :~: ∅)

  val z: ValueOf[:>:[a, :>:[b, nrec]]] = abAgain := zz.value
}
```

### CODE REVIEW

**Comment by eparejatobes** [comment]
@laughedelic take a look at it. I kept the two approaches for comparison, the `altRecords` stuff is mostly feature-complete apart from parsing and all that #45. I think we could extract a lesson from here as written in  https://github.com/ohnosequences/cosas/commit/2c95fc29ef970632b46cff91c003921d67f99b3e

**Comment by eparejatobes** [comment]
TODO here:

- [ ] review if there's something missing in the new approach
- [ ] add refinements for `AnyRecordType`
- [ ] remove property holders
- [ ] remove the old approach
- [ ] remove parsing, will be done in #45

**Comment by eparejatobes** [comment]
done! just a couple of small things.

- [ ] find a better name/symbol for empty record
- [ ] rename :@: (the class) to record cons
- [ ] is it a good idea to use the same :~: symbol for constructing records?

**Comment by eparejatobes** [comment]
published as `0.7.0-simpler-records`.

**Comment by laughedelic** [comment]
Hi! I kind was kind of in the :airplane:-mode.. 😅
This looks nice! Only names are a bit confusing for me. A couple of suggestions:
- what is now called `Record` I would rather name `Fields`
- then you can say just `Record` for what is `RecordType` now
- probably `NoFields`/`NFields` for empty fields set?
- I don't think using `:~:` is a good idea, because then it looks like a typeset, but it's not. I'm fine with anything else `:@:`, `:^:`, `:&:`...

For example:
```scala
case object simpleUser extends Record(id :^: name :^: NFields)
case object normalUser extends Record(email :^: color :^: simpleUser.fields)
```

**Comment by eparejatobes** [comment]
Fine! see #51

**Comment by laughedelic** [comment]
Have you published it?

**Comment by eparejatobes** [comment]
yes. Are we still following the `ops` convention? if so I need to move all the get update stuff

**Comment by eparejatobes** [comment]
I want to finish with this so that I can update parsing. Is there anything important missing?

**Comment by laughedelic** [comment]
Let's finish https://github.com/era7bio/project-utils/pull/8 first, then we will see if something is missing

**Pull request merged**
