### PR TITLE
Improve docs a bit

### PR DESCRIPTION
**Pull request by eparejatobes**

### CODE REVIEW

**Comment by eparejatobes** [comment]
@laughedelic I separated `subsetTypes` into a different object, things are clearer now I think. Is there something else that you'd like to see in `0.6.0`?? What about a good `show`?

**Comment by laughedelic** [comment]
Good show is definitely a necessary thing. But if we're not using some show instance from whatever else, then why not just using `toString`?

**Comment by laughedelic** [comment]
what's this? should we try to merge it?

**Comment by eparejatobes** [comment]
It would be nice to pick some parts of it. It is probably easier to do it manually.

**Pull request closed without merging**
