### PR TITLE
predicates are wrong; they are fixable though

### PR DESCRIPTION
**Pull request by eparejatobes**
- [x] Predicate should be fn1 with out Unit
- [x] and/or OK; not impossible
- [ ] need to resort to ambiguity for cases like not subtype of

### CODE REVIEW

**Comment by eparejatobes** [comment]
mostly finished. Will update subtype etc in a separate PR

**Comment by eparejatobes** [comment]
notSubtype does not work for who knows what reason. I guess aliasing package objects or who knows what.

**Comment by eparejatobes** [comment]
@laughedelic what do you think of this? I guess better to leave all subtyping relations as they where, and use them in predicates when needed.

**Comment by eparejatobes** [comment]
LGTM

**Comment by laughedelic** [comment]
Sorry, I forgot to reply. Yep, I agree with leaving old sub/notSub. I made some minor changes. LGTM

**Pull request merged**
