### PR TITLE
view-based type-level equality

### PR DESCRIPTION
**Pull request by eparejatobes**

### CODE REVIEW

**Comment by eparejatobes** [comment]
@laughedelic just so you know my plans: I want to use this in Scarph, already tested there; I think it's a pretty useful tool. It needs a bit of polishing and testing though.

**Comment by laughedelic** [comment]
@eparejatobes ok, nice :+1:

**Comment by laughedelic** [comment]
Are you doing it in the `experiment/paths/as/graph/types` branch?

**Comment by eparejatobes** [comment]
you can publish and use this branch there

**Comment by laughedelic** [comment]
Ok, but I think as it's not crucial for other stuff in scarph, I will wait for this branch to be merged here first.

**Comment by eparejatobes** [comment]
I'm merging this, it is solid enough. The names can be changed later if needed.

**Pull request merged**
