### PR TITLE
Parsing is wrong

### PR DESCRIPTION
**Pull request by eparejatobes**
It should return `Either[...]`

### CODE REVIEW

**Comment by eparejatobes** [comment]
this is waiting for #49

**Comment by laughedelic** [comment]
#49 is merged

**Comment by eparejatobes** [comment]
fine I'm going to update this

**Comment by eparejatobes** [comment]
a simple version which doesn't accumulate errors. I'm actually not that sure of the usefulness of accumulating them here. @laughedelic take a look at it

**Comment by eparejatobes** [comment]
After @laughedelic OK and adding some more tests, LGTM

**Comment by laughedelic** [comment]
Ok, I'm reviewing this

**Comment by laughedelic** [comment]
Couldn't comment on the diff:
- `  // TODO aliases for matching etc` — what's that about?
- `  // TODO review this symbol; I'm fine with any other` about `:&:` — I'm fine with it. Although I think we could use same `:~:`, because the `:~: FNil` or `:~: □` distinguishes fields enough..

**Comment by eparejatobes** [comment]
1. I'm fine with it, but then what would happen when importing `typeSets._, records._`?
2. withValues ok
3. there was something wrong with that, I don't remember what. Let's try and see
4. and then what's the point of `AnyRecord`? the idea is to separate those two aspects (the set of properties and corresponding values, and a `Type` denoted by that).

**Comment by laughedelic** [comment]
1. I think there is no problem here, you don't ever use `:~:` symbol on its own. But when applied it's unambiguous.
2. ok ok
3. ok
4. the point of record is to be able to refer to fields in a convenient way. fields being a type doesn't cost us anything, what's the point of forbidding it?

**Comment by laughedelic** [comment]
:stars:

**Comment by laughedelic** [comment]
Another thing: 
5. I would rename `AnyFields` to `AnyPropertySet`. We have too many names and "fields" is confusing, because there is no such thing as "a field". Plus inside of it, it's still a set of properties. Same as with `AnyDataSet` in project-utils: a set of `AnyData`s.

**Comment by eparejatobes** [comment]
You do use it, as a type: `X = H :~: T` and now what's that if `H` is a property?. OK about `AnyFields`.

**Comment by eparejatobes** [comment]
I moved it back to records and forgot to remove it from ops :)

**Comment by laughedelic** [comment]
> You do use it, as a type: X = H :~: T and now what's that if H is a property

ok. I fine with the current symbol.

**Comment by eparejatobes** [comment]
so what's left here? mergemergemerge

**Comment by laughedelic** [comment]
LGTM

**Comment by eparejatobes** [comment]
ok

**Pull request merged**
